if(!hs){var hs={lang:{cssDirection:"ltr",loadingText:"Loading...",loadingTitle:"Click to cancel",restoreTitle:"Click to close image"},graphicsDir:"highslide/graphics/",expandCursor:"zoomin.cur",restoreCursor:"zoomout.cur",expandDuration:250,restoreDuration:250,marginLeft:15,marginRight:15,marginTop:15,marginBottom:15,zIndexCounter:1001,loadingOpacity:0.75,transitions:[],transitionDuration:250,dimmingOpacity:0,dimmingDuration:50,minWidth:200,minHeight:200,expanders:[],overrides:"transitions dimmingOpacity wrapperClassName minWidth minHeight maxWidth maxHeight pageOrigin slideshowGroup easing easingClose fadeInOut src".split(" "),
timers:[],clones:{},onReady:[],uaVersion:/Trident\/4\.0/.test(navigator.userAgent)?8:parseFloat((navigator.userAgent.toLowerCase().match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[0,"0"])[1]),ie:document.all&&!window.opera,safari:/Safari/.test(navigator.userAgent),geckoMac:/Macintosh.+rv:1\.[0-8].+Gecko/.test(navigator.userAgent),$:function(a){if(a)return document.getElementById(a)},push:function(a,b){a[a.length]=b},createElement:function(a,b,c,d,h){a=document.createElement(a);b&&hs.extend(a,b);h&&hs.setStyles(a,
{padding:0,border:"none",margin:0});c&&hs.setStyles(a,c);d&&d.appendChild(a);return a},extend:function(a,b){for(var c in b)a[c]=b[c];return a},setStyles:function(a,b){for(var c in b)hs.ieLt9&&"opacity"==c?0.99<b[c]?a.style.removeAttribute("filter"):a.style.filter="alpha(opacity="+100*b[c]+")":a.style[c]=b[c]},animate:function(a,b,c){var d,h,f;if("object"!=typeof c||null===c)d=arguments,c={duration:d[2],easing:d[3],complete:d[4]};"number"!=typeof c.duration&&(c.duration=250);c.easing=Math[c.easing]||
Math.easeInQuad;c.curAnim=hs.extend({},b);for(var g in b){var k=new hs.fx(a,c,g);d=parseFloat(hs.css(a,g))||0;h=parseFloat(b[g]);f="opacity"!=g?"px":"";k.custom(d,h,f)}},css:function(a,b){if(a.style[b])return a.style[b];if(document.defaultView)return document.defaultView.getComputedStyle(a,null).getPropertyValue(b);"opacity"==b&&(b="filter");var c=a.currentStyle[b.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()})];"filter"==b&&(c=c.replace(/alpha\(opacity=([0-9]+)\)/,function(a,b){return b/
100}));return""===c?1:c},getPageSize:function(){var a=document,b=a.compatMode&&"BackCompat"!=a.compatMode?a.documentElement:a.body,c=hs.ie&&(9>hs.uaVersion||"undefined"==typeof pageXOffset);hs.page={width:c?b.clientWidth:a.documentElement.clientWidth||self.innerWidth,height:c?b.clientHeight:self.innerHeight,scrollLeft:c?b.scrollLeft:pageXOffset,scrollTop:c?b.scrollTop:pageYOffset};return hs.page},getPosition:function(a){for(var b={x:a.offsetLeft,y:a.offsetTop};a.offsetParent;)a=a.offsetParent,b.x+=
a.offsetLeft,b.y+=a.offsetTop,a!=document.body&&a!=document.documentElement&&(b.x-=a.scrollLeft,b.y-=a.scrollTop);return b},expand:function(a,b,c,d){a||(a=hs.createElement("a",null,{display:"none"},hs.container));if("function"==typeof a.getParams)return b;try{return new hs.Expander(a,b,c),!1}catch(h){return!0}},getParam:function(a,b){a.getParams=a.onclick;var c=a.getParams?a.getParams():null;a.getParams=null;return c&&"undefined"!=typeof c[b]?c[b]:"undefined"!=typeof hs[b]?hs[b]:null},getSrc:function(a){var b=
hs.getParam(a,"src");return b?b:a.href},discardElement:function(a){a&&hs.garbageBin.appendChild(a);hs.garbageBin.innerHTML=""},dim:function(a){if(!hs.dimmer&&(c=!0,hs.dimmer=hs.createElement("div",{className:"highslide-dimming highslide-viewport-size",owner:"",onclick:function(){hs.close()}},{visibility:"visible",opacity:0},hs.container,!0),/(Android|iPad|iPhone|iPod)/.test(navigator.userAgent))){var b=document.body,c=function(){hs.setStyles(hs.dimmer,{width:b.scrollWidth+"px",height:b.scrollHeight+
"px"})};c();hs.addEventListener(window,"resize",c)}hs.dimmer.style.display="";var c=""==hs.dimmer.owner;hs.dimmer.owner+="|"+a.key;c&&(hs.geckoMac&&hs.dimmingGeckoFix?hs.setStyles(hs.dimmer,{background:"url("+hs.graphicsDir+"geckodimmer.png)",opacity:1}):hs.animate(hs.dimmer,{opacity:a.dimmingOpacity},hs.dimmingDuration))},undim:function(a){hs.dimmer&&("undefined"!=typeof a&&(hs.dimmer.owner=hs.dimmer.owner.replace("|"+a,"")),"undefined"!=typeof a&&""!=hs.dimmer.owner||hs.upcoming&&hs.getParam(hs.upcoming,
"dimmingOpacity")||(hs.geckoMac&&hs.dimmingGeckoFix?hs.dimmer.style.display="none":hs.animate(hs.dimmer,{opacity:0},hs.dimmingDuration,null,function(){hs.dimmer.style.display="none"})))},getWrapperKey:function(a,b){var c,d=/^highslide-wrapper-([0-9]+)$/;for(c=a;c.parentNode;){if(c.id&&d.test(c.id))return c.id.replace(d,"$1");c=c.parentNode}if(!b)for(c=a;c.parentNode;){if(c.tagName&&hs.isHsAnchor(c))for(d=0;d<hs.expanders.length;d++){var h=hs.expanders[d];if(h&&h.a==c)return d}c=c.parentNode}return null},
getExpander:function(a,b){if("undefined"==typeof a)return hs.expanders[hs.focusKey]||null;if("number"==typeof a)return hs.expanders[a]||null;"string"==typeof a&&(a=hs.$(a));return hs.expanders[hs.getWrapperKey(a,b)]||null},isHsAnchor:function(a){return a.onclick&&a.onclick.toString().replace(/\s/g," ").match(/hs.(htmlE|e)xpand/)},addEventListener:function(a,b,c){a==document&&"ready"==b&&hs.push(hs.onReady,c);try{a.addEventListener(b,c,!1)}catch(d){try{a.detachEvent("on"+b,c),a.attachEvent("on"+b,
c)}catch(h){a["on"+b]=c}}},removeEventListener:function(a,b,c){try{a.removeEventListener(b,c,!1)}catch(d){try{a.detachEvent("on"+b,c)}catch(h){a["on"+b]=null}}},init:function(){if(!hs.container){hs.ieLt7=hs.ie&&7>hs.uaVersion;hs.ieLt9=hs.ie&&9>hs.uaVersion;hs.getPageSize();for(var a in hs.langDefaults)"undefined"!=typeof hs[a]?hs.lang[a]=hs[a]:"undefined"==typeof hs.lang[a]&&"undefined"!=typeof hs.langDefaults[a]&&(hs.lang[a]=hs.langDefaults[a]);hs.container=hs.createElement("div",{className:"highslide-container"},
{position:"absolute",left:0,top:0,width:"100%",zIndex:hs.zIndexCounter,direction:"ltr"},document.body,!0);hs.loading=hs.createElement("a",{className:"highslide-loading",title:hs.lang.loadingTitle,innerHTML:hs.lang.loadingText,href:"javascript:;"},{position:"absolute",top:"-9999px",opacity:hs.loadingOpacity,zIndex:1},hs.container);hs.garbageBin=hs.createElement("div",null,{display:"none"},hs.container);Math.linearTween=function(a,c,d,h){return d*a/h+c};Math.easeInQuad=function(a,c,d,h){return d*(a/=
h)*a+c}}},ready:function(){if(!hs.isReady){hs.isReady=!0;for(var a=0;a<hs.onReady.length;a++)hs.onReady[a]()}},close:function(a){(a=hs.getExpander(a))&&a.close();return!1},fx:function(a,b,c){this.options=b;this.elem=a;this.prop=c;b.orig||(b.orig={})}};hs.fx.prototype={update:function(){(hs.fx.step[this.prop]||hs.fx.step._default)(this);this.options.step&&this.options.step.call(this.elem,this.now,this)},custom:function(a,b,c){function d(a){return h.step(a)}this.startTime=(new Date).getTime();this.start=
a;this.end=b;this.unit=c;this.now=this.start;this.pos=this.state=0;var h=this;d.elem=this.elem;d()&&1==hs.timers.push(d)&&(hs.timerId=setInterval(function(){for(var a=hs.timers,b=0;b<a.length;b++)a[b]()||a.splice(b--,1);a.length||clearInterval(hs.timerId)},13))},step:function(a){var b=(new Date).getTime();if(a||b>=this.options.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();a=this.options.curAnim[this.prop]=!0;for(var c in this.options.curAnim)!0!==this.options.curAnim[c]&&
(a=!1);a&&this.options.complete&&this.options.complete.call(this.elem);return!1}c=b-this.startTime;this.state=c/this.options.duration;this.pos=this.options.easing(c,0,1,this.options.duration);this.now=this.start+(this.end-this.start)*this.pos;this.update();return!0}};hs.extend(hs.fx,{step:{opacity:function(a){hs.setStyles(a.elem,{opacity:a.now})},_default:function(a){try{a.elem.style&&null!=a.elem.style[a.prop]?a.elem.style[a.prop]=a.now+a.unit:a.elem[a.prop]=a.now}catch(b){}}}});hs.Dimension=function(a,
b){this.exp=a;this.dim=b;this.ucwh="x"==b?"Width":"Height";this.wh=this.ucwh.toLowerCase();this.uclt="x"==b?"Left":"Top";this.lt=this.uclt.toLowerCase();this.ucrb="x"==b?"Right":"Bottom";this.rb=this.ucrb.toLowerCase()};hs.Dimension.prototype={get:function(a){switch(a){case "loadingPos":return this.tpos+this.tb+(this.t-hs.loading["offset"+this.ucwh])/2;case "loadingPosXfade":return this.pos+this.cb+(this.size-hs.loading["offset"+this.ucwh])/2;case "wsize":return this.size+2*this.cb;case "fitsize":return this.clientSize-
this.marginMin-this.marginMax;case "maxsize":return this.get("fitsize")-2*this.cb;case "opos":return this.pos;case "osize":return this.get("wsize")}},calcBorders:function(){this.cb=(this.exp.content["offset"+this.ucwh]-this.t)/2;this.marginMax=hs["margin"+this.ucrb]},calcThumb:function(){this.t=this.exp.el[this.wh]?parseInt(this.exp.el[this.wh]):this.exp.el["offset"+this.ucwh];this.tpos=this.exp.tpos[this.dim];this.tb=(this.exp.el["offset"+this.ucwh]-this.t)/2;if(0==this.tpos||-1==this.tpos)this.tpos=
hs.page[this.wh]/2+hs.page["scroll"+this.uclt]},calcExpanded:function(){var a=this.exp;this.justify="auto";this.pos=this.tpos-this.cb+this.tb;this.maxHeight&&"x"==this.dim&&(a.maxWidth=Math.min(a.maxWidth||this.full,a.maxHeight*this.full/a.y.full));this.size=Math.min(this.full,a["max"+this.ucwh]||this.full);this.minSize=this.full;this.marginMin=hs["margin"+this.uclt];this.scroll=hs.page["scroll"+this.uclt];this.clientSize=hs.page[this.wh]},setSize:function(a){var b=this.exp;this.size=a;b.content.style[this.wh]=
a+"px";b.wrapper.style[this.wh]=this.get("wsize")+"px"},setPos:function(a){this.pos=a;this.exp.wrapper.style[this.lt]=a+"px"}};hs.Expander=function(a,b,c,d){if(document.readyState&&hs.ie&&!hs.isReady)hs.addEventListener(document,"ready",function(){new hs.Expander(a,b,c,d)});else{this.a=a;this.custom=c;this.contentType=d||"image";this.isImage=!this.isHtml;this.last=hs.last;hs.last=null;hs.init();for(var h=this.key=hs.expanders.length,f=0;f<hs.overrides.length;f++){var g=hs.overrides[f];this[g]=b&&
"undefined"!=typeof b[g]?b[g]:hs[g]}this.src||(this.src=a.href);g=b&&b.thumbnailId?hs.$(b.thumbnailId):a;g=this.thumb=g.getElementsByTagName("img")[0]||g;this.thumbsUserSetId=g.id||a.id;for(f=0;f<hs.expanders.length;f++)if(hs.expanders[f]&&hs.expanders[f].a==a&&!(this.last&&"crossfade"==this.transitions[1]))return hs.expanders[f].focus(),!1;if(!hs.allowSimultaneousLoading)for(f=0;f<hs.expanders.length;f++)hs.expanders[f]&&(hs.expanders[f].thumb!=g&&!hs.expanders[f].onLoadStarted)&&hs.expanders[f].cancelLoading();
hs.expanders[h]=this;hs.expanders[h-1]&&hs.expanders[h-1].close();"undefined"!=typeof hs.focusKey&&hs.expanders[hs.focusKey]&&hs.expanders[hs.focusKey].close();this.el=g;this.tpos=this.pageOrigin||hs.getPosition(g);hs.getPageSize();(this.x=new hs.Dimension(this,"x")).calcThumb();(this.y=new hs.Dimension(this,"y")).calcThumb();this.wrapper=hs.createElement("div",{id:"highslide-wrapper-"+this.key,className:"highslide-wrapper "+this.wrapperClassName},{visibility:"hidden",position:"absolute",zIndex:hs.zIndexCounter+=
2},null,!0);this[this.contentType+"Create"]();return!0}};hs.Expander.prototype={error:function(a){hs.debug?alert("Line "+a.lineNumber+": "+a.message):window.location.href=this.src},showLoading:function(){if(!this.onLoadStarted&&!this.loading){this.loading=hs.loading;var a=this;this.loading.onclick=function(){a.cancelLoading()};var a=this,b=this.x.get("loadingPos")+"px",c=this.y.get("loadingPos")+"px";if(!d&&this.last&&"crossfade"==this.transitions[1])var d=this.last;d&&(b=d.x.get("loadingPosXfade")+
"px",c=d.y.get("loadingPosXfade")+"px",this.loading.style.zIndex=hs.zIndexCounter++);setTimeout(function(){a.loading&&hs.setStyles(a.loading,{left:b,top:c,zIndex:hs.zIndexCounter++})},100)}},imageCreate:function(){var a=this,b=document.createElement("img");this.content=b;b.onload=function(){hs.expanders[a.key]&&a.contentLoaded()};b.onclick=function(){try{a.close()}catch(b){}};hs.blockRightClick&&(b.oncontextmenu=function(){return!1});b.className="highslide-image";hs.setStyles(b,{visibility:"hidden",
display:"block",position:"absolute",maxWidth:"9999px",zIndex:3});b.title=hs.lang.restoreTitle;hs.safari&&525>hs.uaVersion&&hs.container.appendChild(b);hs.ie&&hs.flushImgSize&&(b.src=null);b.src=this.src;this.showLoading()},contentLoaded:function(){try{if(this.content&&(this.content.onload=null,!this.onLoadStarted)){this.onLoadStarted=!0;var a=this.x,b=this.y;this.loading&&(hs.setStyles(this.loading,{top:"-9999px"}),this.loading=null);a.full=this.content.width;b.full=this.content.height;hs.setStyles(this.content,
{width:a.t+"px",height:b.t+"px"});this.wrapper.appendChild(this.content);hs.container.appendChild(this.wrapper);a.calcBorders();b.calcBorders();hs.setStyles(this.wrapper,{left:a.tpos+a.tb-a.cb+"px",top:b.tpos+a.tb-b.cb+"px"});a.calcExpanded();this.justify(a);b.calcExpanded();this.justify(b);this.show()}}catch(c){this.error(c)}},justify:function(a,b){var c=!1;a.pos=Math.round(a.pos-(a.get("wsize")-a.t)/2);a.pos<a.scroll+a.marginMin&&(a.pos=a.scroll+a.marginMin,c=!0);if(a.pos+a.get("wsize")>a.scroll+
a.clientSize-a.marginMax&&(b||!c))a.get("wsize")<a.get("fitsize")?a.pos=a.scroll+a.clientSize-a.marginMax-a.get("wsize"):a.pos=a.scroll+a.marginMin;a.pos<a.marginMin&&(a.pos=a.marginMin)},show:function(){var a=this.x,b=this.y;this.changeSize(1,{wrapper:{width:a.get("wsize"),height:b.get("wsize"),left:a.pos,top:b.pos},content:{width:a.size,height:b.size}},hs.expandDuration)},changeSize:function(a,b,c){var d=this.transitions,h=a?this.last?this.last.a:null:hs.upcoming,d=d[1]&&h&&hs.getParam(h,"transitions")[1]==
d[1]?d[1]:d[0];if(this[d]&&"expand"!=d)this[d](a,b);else{var f=this,d=f.x,h=f.y,g=this.easing;a||(g=this.easingClose||g);var k=a?function(){setTimeout(function(){f.afterExpand()},50)}:function(){f.afterClose()};a&&hs.setStyles(this.wrapper,{width:d.t+"px",height:h.t+"px"});this.fadeInOut&&(hs.setStyles(this.wrapper,{opacity:a?0:1}),hs.extend(b.wrapper,{opacity:a}));hs.animate(this.wrapper,b.wrapper,{duration:c,easing:g,step:function(a,b){}});hs.animate(this.content,b.content,c,g,k);a&&(this.wrapper.style.visibility=
"visible",this.content.style.visibility="visible",this.a.className+=" highslide-active-anchor")}},fade:function(a,b){var c=this,d=a?hs.expandDuration:0;a&&(hs.animate(this.wrapper,b.wrapper,0),hs.setStyles(this.wrapper,{opacity:0,visibility:"visible"}),hs.animate(this.content,b.content,0),this.content.style.visibility="visible",hs.animate(this.wrapper,{opacity:1},d,null,function(){c.afterExpand()}));a||setTimeout(function(){hs.animate(c.wrapper,{opacity:0},hs.restoreDuration,null,function(){c.afterClose()})},
d)},crossfade:function(a,b,c){if(a){var d=this,h=this.last,f=this.x,g=this.y,k=h.x,l=h.y,r=this.wrapper,s=this.content;hs.setStyles(s,{width:(f.imgSize||f.size)+"px",height:(g.imgSize||g.size)+"px"});var q=hs.createElement("div",{className:"highslide-"+this.contentType},{position:"absolute",zIndex:4,overflow:"hidden",display:"none"});a={oldImg:h,newImg:this};for(var m in a)this[m]=a[m].content.cloneNode(1),hs.setStyles(this[m],{position:"absolute",border:0,visibility:"visible"}),q.appendChild(this[m]);
r.appendChild(q);q.style.display="";h.content.style.display="none";hs.safari&&525>hs.uaVersion&&(this.wrapper.style.visibility="visible");hs.animate(r,{width:f.size},{duration:hs.transitionDuration,step:function(a,b){var c=b.pos,p=1-c,n,e={},m=["pos","size","p1","p2"],t;for(t in m)n=m[t],e["x"+n]=Math.round(p*k[n]+c*f[n]),e["y"+n]=Math.round(p*l[n]+c*g[n]),e.ximgSize=Math.round(p*(k.imgSize||k.size)+c*(f.imgSize||f.size)),e.ximgPad=Math.round(p*k.get("imgPad")+c*f.get("imgPad")),e.yimgSize=Math.round(p*
(l.imgSize||l.size)+c*(g.imgSize||g.size)),e.yimgPad=Math.round(p*l.get("imgPad")+c*g.get("imgPad"));h.wrapper.style.clip="rect("+(e.ypos-l.pos)+"px, "+(e.xsize+e.xp1+e.xp2+e.xpos+2*k.cb-k.pos)+"px, "+(e.ysize+e.yp1+e.yp2+e.ypos+2*l.cb-l.pos)+"px, "+(e.xpos-k.pos)+"px)";hs.setStyles(s,{top:e.yp1+g.get("imgPad")+"px",left:e.xp1+f.get("imgPad")+"px",marginTop:g.pos-e.ypos+"px",marginLeft:f.pos-e.xpos+"px"});hs.setStyles(r,{top:e.ypos+"px",left:e.xpos+"px",width:e.xp1+e.xp2+e.xsize+2*f.cb+"px",height:e.yp1+
e.yp2+e.ysize+2*g.cb+"px"});hs.setStyles(q,{width:(e.ximgSize||e.xsize)+"px",height:(e.yimgSize||e.ysize)+"px",left:e.xp1+e.ximgPad+"px",top:e.yp1+e.yimgPad+"px",visibility:"visible"});hs.setStyles(d.oldImg,{top:l.pos-e.ypos+l.p1-e.yp1+l.get("imgPad")-e.yimgPad+"px",left:k.pos-e.xpos+k.p1-e.xp1+k.get("imgPad")-e.ximgPad+"px"});hs.setStyles(d.newImg,{opacity:c,top:g.pos-e.ypos+g.p1-e.yp1+g.get("imgPad")-e.yimgPad+"px",left:f.pos-e.xpos+f.p1-e.xp1+f.get("imgPad")-e.ximgPad+"px"})},complete:function(){r.style.visibility=
s.style.visibility="visible";s.style.display="block";hs.discardElement(q);d.afterExpand();h.afterClose();d.last=null}})}},reuseOverlay:function(a,b){if(!this.last)return!1;for(var c=0;c<this.last.overlays.length;c++){var d=hs.$("hsId"+this.last.overlays[c]);if(d&&d.hsId==a.hsId)return this.genOverlayBox(),d.reuse=this.key,hs.push(this.overlays,this.last.overlays[c]),!0}return!1},afterExpand:function(){this.isExpanded=!0;this.focus();this.dimmingOpacity&&hs.dim(this)},cancelLoading:function(){hs.discardElement(this.wrapper);
hs.expanders[this.key]=null;hs.upcoming==this.a&&(hs.upcoming=null);hs.undim(this.key);this.loading&&(hs.loading.style.left="-9999px")},focus:function(){this.wrapper.style.zIndex=hs.zIndexCounter+=2;this.content.title=hs.lang.restoreTitle;hs.restoreCursor&&(hs.styleRestoreCursor=window.opera?"pointer":"url("+hs.graphicsDir+hs.restoreCursor+"), pointer",hs.ieLt7&&6>hs.uaVersion&&(hs.styleRestoreCursor="hand"),this.content.style.cursor=hs.styleRestoreCursor);hs.focusKey=this.key},close:function(){if(!this.isClosing&&
this.isExpanded){"crossfade"==this.transitions[1]&&hs.upcoming&&(hs.getExpander(hs.upcoming).cancelLoading(),hs.upcoming=null);this.isClosing=!0;try{this.content.style.cursor="default",this.changeSize(0,{wrapper:{width:this.x.t,height:this.y.t,left:this.x.tpos-this.x.cb+this.x.tb,top:this.y.tpos-this.y.cb+this.y.tb},content:{width:this.x.t,height:this.y.t}},hs.restoreDuration)}catch(a){this.afterClose()}}},afterClose:function(){this.a.className=this.a.className.replace("highslide-active-anchor","");
hs.discardElement(this.wrapper);this.dimmingOpacity&&hs.undim(this.key);hs.expanders[this.key]=null}};hs.langDefaults=hs.lang;var HsExpander=hs.Expander;hs.ie&&window==window.top&&function(){try{document.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,50);return}hs.ready()}();hs.addEventListener(document,"DOMContentLoaded",hs.ready);hs.addEventListener(window,"load",hs.ready);hs.addEventListener(document,"ready",function(){if(hs.expandCursor||hs.dimmingOpacity){var a=hs.createElement("style",
{type:"text/css"},null,document.getElementsByTagName("HEAD")[0]),b="BackCompat"==document.compatMode,c=function(c,d){if(hs.ie&&(9>hs.uaVersion||b)){var g=document.styleSheets[document.styleSheets.length-1];"object"==typeof g.addRule&&g.addRule(c,d)}else a.appendChild(document.createTextNode(c+" {"+d+"}"))},d=function(a){return"expression( ( ( ignoreMe = document.documentElement."+a+" ? document.documentElement."+a+" : document.body."+a+" ) ) + 'px' );"};hs.expandCursor&&c(".highslide img","cursor: url("+
hs.graphicsDir+hs.expandCursor+"), pointer !important;");c(".highslide-viewport-size",hs.ie&&(7>hs.uaVersion||b)?"position: absolute; left:"+d("scrollLeft")+"top:"+d("scrollTop")+"width:"+d("clientWidth")+"height:"+d("clientHeight"):"position: fixed; width: 100%; height: 100%; left: 0; top: 0")}});hs.addEventListener(window,"resize",function(){hs.getPageSize()})};
